### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by star0202** [star0202/Alicea#9]
- [x] 버튼으로 역할 지급
- [ ] 유저 approve
- [x] 이미 log channel인 채널에서 `/log set` 사용시 log channel 비활성화
- [x] 음성채널 join leave 로거
- [ ] ./record <channel> 음성채널에 봇 참가시키고 녹음해서 wav export -> 채널에 녹음중이라는거 표현하기
